version: "2.2"
services:
  web:
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"

    #command: mongoimport --db mongo --collection products C:\Users\Softsuave\Desktop\AR\ar-backend\products.json
    #command: mongoimport --db mongo --collection users C:\Users\Softsuave\Desktop\AR\ar-backend\users.json


